# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helwan', '0007_auto_20180129_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenow', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deadline', models.DateField(blank=True)),
                ('per', models.FloatField()),
            ],
        ),
    ]
