# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helwan', '0008_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='datenow',
        ),
    ]
