# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helwan', '0009_remove_set_datenow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='set',
            new_name='perc',
        ),
    ]
