# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helwan', '0011_auto_20180203_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perc',
            old_name='per',
            new_name='computerper',
        ),
    ]
